s = '我叫{}, 今年{}, 爱好{}'.format('太保', 36, 'girl')
print(s)
s1 = '我叫{0}, 今年{1}, 爱好{2}, 再说一下我叫{0}'.format('太保', 36, 'girl')
print(s1)
s2 = '我叫{name}, 今年{age}, 爱好{hobbie}'.format(age=36, hobbie='girl', name='太保')
print(s2)